baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'harshc_'
theme="archie"
googleAnalytics = "G-FWMFRC7NTP"
copyright = '© Harsh Chauhan'

# Code Highlight
pygmentsstyle = 'monokai'
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=9 # articles per page

[params]
	favicon = '/support/h.png'
        mode='toggle' # color-mode → dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = ''
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

# Social Tags

[[params.social]]
name = 'GitHub'
icon = 'github'
url = 'https://github.com/iharshchauhan'

[[params.social]]
name = 'Twitter'
icon = 'twitter'
url = 'https://twitter.com/harshc_/'

[[params.social]]
name = 'Instagram'
icon = 'instagram'
url = 'https://instagram.com/iharshchauhan/'

[[params.social]]
name = 'Spotify'
icon = 'music'
url = 'https://open.spotify.com/playlist/6rhg71awO0tB2GIunqOxAg?si=b1cb737056354412'

# Main menu Items

[[menu.main]]
name = 'Logbook'
url = '/posts'
weight = 2

[[menu.main]]
name = 'About'
url = '/about'
weight = 1

[[menu.main]]
name = 'Library'
url = '/tags'
weight = 3
